modLoader = "javafml"
loaderVersion = "[41,)"
issueTrackerURL = "https://github.com/ImUrX/localizedbrowsing/issues"
license = "MIT OR Apache-2.0"

[[mods]]
modId = "interrecipebrowser"
version = "${version}"
displayName = "Localized Browsing"
authors = "ImUrX"
credits = "KANJIDIC Project https://www.edrdg.org/wiki/index.php/KANJIDIC_Project"
description = '''
Let's you search without using any graphemes!
'''
logoFile = "icon.png"
displayTest = "IGNORE_ALL_VERSION"

[[dependencies.interrecipebrowser]]
modId = "forge"
mandatory = true
versionRange = "[41,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.interrecipebrowser]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19,)"
ordering = "NONE"
side = "BOTH"
