modLoader = "javafml"
loaderVersion = "[43,)"
issueTrackerURL = "https://github.com/ImUrX/localizedbrowsing/issues"
license = "MIT OR Apache-2.0"

[[mods]]
modId = "localizedbrowser"
version = "${version}"
displayName = "Better Locale"
authors = "ImUrX"
credits = '''
Thank you to:
jaredlll08
Acknowledgements:
atilika/kuromoji <https://github.com/atilika/kuromoji/>
'''
description = '''
Let's you search without using any graphemes!
'''
logoFile = "icon.png"
updateJSONURL = "https://api.modrinth.com/updates/localized-browser/forge_updates.json"
displayTest = "IGNORE_ALL_VERSION"

[[dependencies.localizedbrowser]]
modId = "forge"
mandatory = true
versionRange = "[43,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.localizedbrowser]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19.2,)"
ordering = "NONE"
side = "BOTH"
