modLoader = "javafml"
loaderVersion = "[1,)"
issueTrackerURL = "https://github.com/ImUrX/localizedbrowsing/issues"
license = "MIT OR Apache-2.0"

[[mods]]
modId = "localizedbrowser"
version = "${version}"
displayName = "Better Locale"
authors = "ImUrX"
credits = '''
Thank you to:
jaredlll08
Acknowledgements:
atilika/kuromoji <https://github.com/atilika/kuromoji>
esnaultdev/wanakana-kt <https://github.com/esnaultdev/wanakana-kt>
'''
description = "Lets you search without using any graphemes!"
logoFile = "icon.png"
updateJSONURL = "https://api.modrinth.com/updates/better-locale/forge_updates.json?neoforge=only"
displayTest = "IGNORE_ALL_VERSION"

[[mixins]]
config="localizedbrowser.mixins.json"

[[mixins]]
config="localizedbrowser-common.mixins.json"

[[dependencies.localizedbrowser]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.0,)"
ordering = "NONE"
side = "BOTH"
